CSA/urls.py
from django.urls import include, path
from . import views

app_name = 'CSA'

urlpatterns = [
    path('', views.expediton, name='expedition')

]

Stocki/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('stock.urls', namespace='stock')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('client/', include('client.urls', namespace='client')),
    path('CSA/',include('CSA.urls', namespace='CSA')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path
from . import views
app_name='client'
urlpatterns=[
    path('', views.clientform, name='clientform'),
    path('table_client', views.tClients, name='table_client'),

]

stock/urls.py
from django.urls import path
from . import views
from .views import Table_magazine
app_name='stock'
urlpatterns=[
    path('',views.home,name='home'),
    path('stockform',views.stockform ,name='stockform'),
    path('categorieform',views.categorieform ,name='categorieform'),
    path('articleform',views.articleform ,name='articleform'),
    path('table_magazine/',Table_magazine.as_view() ,name='table_magazine'),
    path('sortirform',views.sortirform ,name='sortirform'),
    path('factureform',views.factureform ,name='factureform'),
    path('ajax/load-articles/',views.load_articles,name='load_articles'),
    path('ajax/load-articles_out/',views.load_articles_out,name='load_articles_out'),
    path('ajax/load_stock_out/',views.load_stock_out,name='load_stock_out'),
    path('table_users',views.tableuser,name='table_users'),
    path('table_article',views.tarticle,name='table_article'),
    path('table_categorie',views.tcategorie,name='table_categorie'),
    path('table_stock',views.tstock,name='table_stock'),
    path('table_sortir',views.tsortir,name='table_sortir'),
    path('table_facture',views.tfacture,name='table_facture'),
    path('table_boutique',views.tboutique,name='table_boutique'),
    #vvvvvv
    path('sortir_article/',views.sortir_article,name='sortir_article'),
    path('update_article/<int:id>',views.update_article,name='update_article'),
    path('delete_article/<int:id>',views.delete_article,name='delete_article'),
    path('update_categorie/<int:id>',views.update_categorie,name='update_categorie'),
    path('delete_categorie/<int:id>',views.delete_categorie,name='delete_categorie'),
    path('update_stock/<int:id>',views.update_stock,name='update_stock'),
    path('delete_stock/<int:id>',views.delete_stock,name='delete_stock'),
    path('delete_sortir/<int:id>',views.delete_sortir,name='delete_sortir'),
    path('update_boutique/<int:id>',views.update_boutique,name='update_boutique'),
    path('delete_boutique/<int:id>',views.delete_boutique,name='delete_boutique'),
    path('ajax_delete',views.ajax_delete,name='ajax_delete'),
    path('ajax_update/',views.ajax_update,name='ajax_update'),
    
    path('imprimer_facture/<int:id>',views.imprimer_facture,name='imprimer_facture'),
    path('cart_detail',views.cart_detail,name='cart_detail'),
    path('cart_add/',views.cart_add,name='cart_add'),
    path('cart_remove/<slug:numero>',views.cart_remove,name='cart_remove'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    path('update_item_from_cart/<int:article_num>',views.update_item_from_cart,name='update_item'),

    # path('update_item_from_cart/<int:article_num>',views.update_item_from_cart,name='update_item'),


]

client/models.py
from django.db import models
from django.contrib.auth.models import User
import qrcode
from io import StringIO
from io import BytesIO

from django.core.validators import MinLengthValidator, int_list_validator
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
#models.IntegerField(blank=True)

class Client(models.Model):
     
    nni=models.CharField(unique=True,max_length=10,validators=[int_list_validator(sep=''),MinLengthValidator(10)])
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=20)
    email = models.CharField(max_length=255,null=True)
    adresse=models.CharField(max_length=255,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    tel = models.CharField(max_length=255,null=True)
    qrCode = models.ImageField(upload_to='client/qrcodes/',blank=True, null=True)
    # qrcode = models.ImageField(upload_to='qrcode', blank=True, null=True)

    

    def __str__(self):
        return f"le beneficiaires  {self.nom}/{self.prenom}"


    def save(self, *args, **kwargs):
        qrCode = self.qr_generate(self.nni)
        self.qrCode.save(str(self.nni)+'.png', BytesIO(qrCode), save=False)
        super(Client, self).save(*args, **kwargs)


    @staticmethod
    def qr_generate(nni):
        qr = qrcode.QRCode(
            version=None,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data("somedata" + str(nni))
        qr.make(fit=True)

        qrCode = qr.make_image(fill_color="black", back_color="white")
        qrByte = BytesIO()
        qrCode.save(qrByte)
        return qrByte.getvalue()
    def delivrer_imprimer_carte():
        pass
    def verificationNni():
        pass

client/forms.py
from django import forms
from .models import *

class NewClient(forms.ModelForm):
    class Meta:
        model = Client
        fields ='__all__'  
        exclude =['user','qrCode']
    def __init__(self, *args, **kwargs):
        super(NewClient, self).__init__(*args, **kwargs)
        self.fields['email'].required=False 
        self.fields['adresse'].required=False 
        self.fields['tel'].required=False 

client/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse
from accounts.decorators import admin_and_manager_only
from django.contrib.auth.decorators import login_required
from .forms import NewClient
from django.contrib.auth.models import User
from .models import Client

# Create your views here.

@login_required(login_url='accounts/login')
# @admin_and_manager_only
def clientform(request):
    if request.method == 'POST':
        client_Form = NewClient(request.POST)
        if client_Form.is_valid():
            client_Form= client_Form.save(commit=False)
            client_Form.user = User.objects.get(id=request.user.pk)
            myform=client_Form.save()
            messages.success(request,f"Felicitations la Client  {client_Form.nom}/{client_Form.prenom} est bien ajoute")
            return redirect(reverse('client:clientform'))
    else:
        client_Form = NewClient()
        context={'client_Form' : client_Form}
        return render(request,'client/clientform.html',context)

@login_required(login_url='accounts/login')
@admin_and_manager_only
def tClients(request):
    context={

        'title': 'les Bénéficiaires',
        'tClients': Client.objects.all()

    }
    return render(request,'client/table_client.html',context)

client/templates/client/clientform.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-wrapper">

  <div class="container-fluid">

    <!-- Trigger the modal with a button -->
  <!--  <button type="button" class="btn btn-info p-2 btn-md" data-toggle="modal" data-target="#myModal" title="Ajouter Equipement">+</button>-->
  
    <!-- Modal -->
  <!--  <div class="modal fade" id="myModal" role="dialog">-->
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" >Ajouter des nouvelle Clients </h4>
  
                     <button type="button" class="close" data-dismiss="modal">
                         <a href=""  >&times;</a>
                     </button>
  
  
                       </div>
                     <div class="modal-body">
                           {% if messages %}
                           {% for message in messages %}
                          <div class="alert alert-{{message.tags}}">
                          {{message}}
                          </div>
                             {% endfor %}
                              {% endif %}
                              <!--    form      -->
    <form method="POST">
        {% csrf_token %}
        {{ client_Form|crispy }}
        <!-- <img src="{{ event.qrcode.url }}" alt="Event QR code" /> -->

        <div class="mt-6">
            <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Add</button>
           <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
           </div>

      </form>

      </div>
     <div class="modal-footer">
   <a href=""  >
       <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
          Close
         </button>
        </a>
        </div>


        <!--   endform         -->
       </div>
    </div>
          <!--  </div>-->
   
        </div>
        {% include 'stock/include_footer.html' %}
     </div>
{% endblock content %}
           

client/templates/client/table_client.html
{% extends 'base.html'%}
{% block content %}}

{% load crispy_forms_tags %}

<div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">LIST DES CLIENTS</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="{% url 'stock:home' %}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'client:clientform'%}">Ajouter Un Client</a></li>
                            <li class="breadcrumb-item active" aria-current="page">List Des Clients</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->
                   <div class="row">
                <div class="col-xl-12">
                      <div class="card card-shadow mb-4 ">
                            <div class="card-header border-0">
                                <div class="custom-title-wrap bar-warning">
                                    <div class="custom-title">LIST DES FACTURES </div>
                                    <div class=" widget-action-link">
                                      {% if request.user.is_staff %}

                                        <div class="dropdown">
                                            <a href="#" class="btn btn-transparent text-secondary dropdown-hover p-0" data-toggle="dropdown">
                                                Action <i class="fa fa-caret-down pl-2"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right vl-dropdown">
                                                
                                                <a class="dropdown-item" href="{% url 'stock:home' %}"> Accueil</a>
                                                <a class="dropdown-item" href="{% url 'client:clientform'%}">Ajouter Un Client</a>
                                                <a class="dropdown-item" href="{% url 'client:table_client' %}"> List Des Clients</a>
                                            </div>
                                        </div>
                                         {%endif%}

                                    </div>
                                </div>
                            </div>
                        <div class="card-body- pt-3 pb-4">
                            <div class="table-responsive">
                                {% if request.user.is_staff %}
                                <table id="data_table" class="table table-bordered table-striped" cellspacing="0">

                                    <thead>

                                    <tr>
                                        <th scope="col">NNI </th>
                                        <th scope="col">Nom </th>
                                        <th scope="col">Prenom</th>
                                        <th scope="col">Son Conseiller</th>
                                        <th scope="col"> QRcode </th>
                                       <th scope="col">Genérer Une Cart Temwin</th>
                                       <th scope="col">Supprimer LE Client</th>
                                    </tr>
                                    </thead>
                                    
                                    <tbody>
                                        {% for client in tClients %}
                                        <tr>
                                            <td scope="row">{{client.nni}}</td>
                                            <td scope="row">{{client.nom}}</td>
                                            <td scope="row">{{client.prenom}}</td>
                                            <td scope="row">{{client.user}}</td>
                                            <th scope="row"> <img src="{{client.qr}}" alt="Event QR code" /> </th>
                                            <th>
                                                <!-- Genérer_cart/{{client.id}}/ -->
                                                <a href="#" class="btn btn-primary mb-2 btn-success" >Genérer Cart</a>
                                         
                                            </th>
                                            <th>
                                                <!-- delete_client/{{client.id}} -->
                                                <a href="#" class="btn btn-primary mb-2 btn-success" >SUPPRIMER</a>
                                        
                                            </th>
                                             
                                            <!-- javascript:window.print() -->
                                        </tr>

                                        {%endfor%}
                                    </tbody>

                                </table>
                                {% else %}
                                <table id="data_table" class="table table-bordered table-striped" cellspacing="0">

                                    <thead>

                                    <tr>
                                       <th scope="col"></th>
                                       
                                       <th scope="col">NNI </th>
                                       <th scope="col">Nom </th>
                                       <th scope="col">Prenom</th>
                                       <th scope="col">Son Conseiller</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        {% for client in tClients %}
                                        <tr>
                                            <td scope="row">{{client.nni}}</td>
                                            <td scope="row">{{client.nom}}</td>
                                            <td scope="row">{{client.prenom}}</td>
                                            <td scope="row">{{client.user}}</td>
                                        </tr>

                                        {%endfor%}
                                    </tbody>

                                </table>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
<!--    footer -->
     {% include 'stock/include_footer.html' %}



    </div>

{% endblock content %}