CSA/urls.py
from django.urls import include, path
from . import views

app_name = 'CSA'

urlpatterns = [
    path('', views.expediton, name='expedition')

]

Stocki/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('stock.urls', namespace='stock')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('client/', include('client.urls', namespace='client')),
    path('CSA/',include('CSA.urls', namespace='CSA')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import include, path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', views.loginPage, name='logout'),
    path('login/', views.logoutUser, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    # path('user_update/<int:id>/update', views.user_update, name='user_update')

]

stock/urls.py
from django.urls import path
from . import views
from .views import Table_magazine
app_name='stock'
urlpatterns=[
    path('',views.home,name='home'),
    path('stockform',views.stockform ,name='stockform'),
    path('categorieform',views.categorieform ,name='categorieform'),
    path('articleform',views.articleform ,name='articleform'),
    path('table_magazine/',Table_magazine.as_view() ,name='table_magazine'),
    path('sortirform',views.sortirform ,name='sortirform'),
    path('factureform',views.factureform ,name='factureform'),
    path('ajax/load-articles/',views.load_articles,name='load_articles'),
    path('ajax/load-articles_out/',views.load_articles_out,name='load_articles_out'),
    path('ajax/load_stock_out/',views.load_stock_out,name='load_stock_out'),
    path('table_users',views.tableuser,name='table_users'),
    path('table_article',views.tarticle,name='table_article'),
    path('table_categorie',views.tcategorie,name='table_categorie'),
    path('table_stock',views.tstock,name='table_stock'),
    path('table_sortir',views.tsortir,name='table_sortir'),
    path('table_facture',views.tfacture,name='table_facture'),
    path('table_boutique',views.tboutique,name='table_boutique'),
    #vvvvvv
    path('sortir_article/',views.sortir_article,name='sortir_article'),
    path('update_article/<int:id>',views.update_article,name='update_article'),
    path('delete_article/<int:id>',views.delete_article,name='delete_article'),
    path('update_categorie/<int:id>',views.update_categorie,name='update_categorie'),
    path('delete_categorie/<int:id>',views.delete_categorie,name='delete_categorie'),
    path('update_stock/<int:id>',views.update_stock,name='update_stock'),
    path('delete_stock/<int:id>',views.delete_stock,name='delete_stock'),
    path('delete_sortir/<int:id>',views.delete_sortir,name='delete_sortir'),
    path('update_boutique/<int:id>',views.update_boutique,name='update_boutique'),
    path('delete_boutique/<int:id>',views.delete_boutique,name='delete_boutique'),
    path('ajax_delete',views.ajax_delete,name='ajax_delete'),
    path('ajax_update/',views.ajax_update,name='ajax_update'),
    
    path('imprimer_facture/<int:id>',views.imprimer_facture,name='imprimer_facture'),
    path('cart_detail',views.cart_detail,name='cart_detail'),
    path('cart_add/',views.cart_add,name='cart_add'),
    path('cart_remove/<slug:numero>',views.cart_remove,name='cart_remove'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    path('update_item_from_cart/<int:article_num>',views.update_item_from_cart,name='update_item'),

    # path('update_item_from_cart/<int:article_num>',views.update_item_from_cart,name='update_item'),


]

stock/models.py
from django.db import models
import barcode
import random
import string

from django.dispatch import receiver
from client.models import Client
from django.contrib.auth.models import User
from barcode.writer import ImageWriter
from io import BytesIO
from django.db.models.signals import post_save
from django.core.files import File




class Categorie(models.Model):
    categorie=models.CharField(max_length=20,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    
    
    def __str__(self):
        return self.categorie



Status=(('0','Non'),('1','Oui'))
class Article(models.Model):

    user= models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    numero=models.IntegerField(blank=True)
    # barcode=models.ImageField(upload_to='article/codes',blank=True)
    nom = models.CharField(max_length=20)
    quantity=models.IntegerField(null=True)
    categorie=models.ForeignKey(Categorie,on_delete=models.CASCADE)
    date_entree=models.DateField(null=True,auto_now_add=True)
    prix=models.IntegerField(null=True)
    # statut=models.CharField(max_length=2,null=True,default='0',choices=Status)
    # quantité_en_vrac =models.PositiveIntegerField(null=True)
    duree_conservation=models.DateTimeField(null=True)

    def __str__(self):
        return self.nom

    # def save(self,*args, **kwargs):
    #     if self._state.adding:
    #         EAN =barcode.get_barcode_class('upc')
    #         rend=str(random.randint(2055,99999))
    #         r=str(random.randint(20,1000))
    #         rr=self.categorie.id+self.prix_achat
    #         ean=EAN(str(self.categorie.id)+str(self.user.id)+r+rend+str(self.date_entree.year)+str(self.date_entree.month)+str(self.date_entree.day),writer=ImageWriter())
    #         buffer =BytesIO()
    #         ean.write(buffer)
    #         self.numero=ean.__str__()
    #         self.barcode.save(str({self.nom})+'.png',File(buffer),save=False)
    #     return super().save(*args, **kwargs)
        
class Stock(models.Model):
    qtStock=models.IntegerField()
    # user= models.ForeignKey(User,bla3nk=True,null=True,on_delete=models.CASCADE)
    categorie=models.ForeignKey(Categorie, blank=True,on_delete=models.CASCADE,null=True)
    Article=models.ManyToManyField(Article,blank=True,related_name="article") 
    
    def __str__(self):
        return f"la quantite de Stock: {self.qtStock}"
    
    def gererStock():
        pass
    
class Boutique(models.Model):
    lieu = models.CharField(max_length=32)
    moghataa = models.CharField(max_length=40)
    vendeur=models.OneToOneField(User,on_delete=models.CASCADE)
    # stock=models.OneToOneField(Stock,on_delete=models.CASCADE)
    def extraire_situation_boutique():
        pass
    def genererBel():
        pass

    def __str__(self):
        return str(self.vendeur)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

@receiver(post_save, sender=User)
def create_user_boutique_or_magasine(sender, instance, created, **kwargs):
    if created:
        if not instance.is_superuser:
            if instance.is_staff:
                magasine = Magazine.objects.create(magaziniere=instance)
            else:
                boutique = Boutique.objects.create(vendeur=instance)

class Magazine(models.Model):
    lieu = models.CharField(max_length=32)
    magaziniere = models.ForeignKey(User, on_delete=models.CASCADE)
    # stock=models.OneToOneField(Stock, on_delete=models.CASCADE)
    wilaya = models.CharField(max_length=40)

    def __str__(self):
        return str(self.magaziniere)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

# @receiver(post_save, sender=User)
# def create_user_magasine(sender, instance, created, **kwargs):
#     if created:
#         if instance.is_staff:
#                  if not instance.is_superuser:
#                     magasine = Magazine.objects.create(magaziniere=instance)

class Sortir(models.Model):
    categorie = models.ForeignKey(Categorie,on_delete=models.CASCADE,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    stock=models.ForeignKey(Stock,null=True,on_delete=models.CASCADE)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    qte=models.PositiveIntegerField(null=True)
    prix_sortie=models.FloatField(null=True)
    date_sortie=models.DateField(blank=True,null=True)
    def __str__(self):
        return f"id:{self.id},article:{self.article},la quantité:{self.qte},la prix total:{self.prix_sortie},efectuer par:{self.user}"
    def save(self,*args,**kwargs):
        self.prix_sortie = self.article.prix_achat * self.qte
        return super().save(*args,**kwargs) 
 

class Facture(models.Model):
    dateFacture=models.DateField()
    sorties=models.ManyToManyField(Sortir,related_name='sorties',blank=True)
    User=models.ForeignKey(User,on_delete=models.CASCADE)
    totalprix=models.FloatField(null=True) 

    def __str__(self):
        return f"la prix total est {self.totalprix}"
    def get_sorties(self):
        return self.sorties.all()

class Vente(models.Model):
    date=models.DateTimeField(auto_now_add=True,null=True)
    quantite_vendu=models.PositiveIntegerField(verbose_name="quantite_vendu",null=True)
    client = models.ForeignKey(Client,on_delete=models.CASCADE,null=True)



    def sortir_Article(p):
        pass
    def ticket_de_vente(p):
        pass
    def verificationNni():
        pass
    def respetQuota():
        pass

stock/forms.py
from django import forms
from .models import *
from client.models import Client
from crispy_forms.helper import FormHelper
from django import forms


ARTICLE_QUANTITY_CHOICES=[(i,str(i)) for i in range(1,21)]
UNITE=[('','---------'),('1','individuel'),('En bloc','En bloc')]
class CartAddArticleForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=ARTICLE_QUANTITY_CHOICES,widget=forms.Select({'class':"form-control"}))
    override =forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput())
    unite = forms.TypedChoiceField(required=False, choices=UNITE,widget=forms.Select({'class':"form-control d-print-none"}))
   
class DateInput(forms.DateInput):
    input_type = 'date'
class NewStock(forms.ModelForm):
    class Meta:
        model = Stock
        fields ='__all__'
        exclude=['user','qtStock']
    def __init__(self,user, *args, **kwargs):
        super(NewStock, self).__init__(*args, **kwargs)
        self.fields['categorie'].required = True
        self.fields['categorie'].queryset =Categorie.objects.filter(user=user)
        self.fields['article'].queryset=Article.objects.none()
        if 'categorie' in self.data:
            try:
                categorie_id=int(self.data.get('categorie'))
                self.fields['article'].queryset=Article.objects.filter(categorie=categorie_id).order_by('nom')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['article'].queryset=self.instance.categorie.article_set.order_by('nom')
        


class NewCategorie(forms.ModelForm):
    class Meta:
        model = Categorie
        fields =['categorie']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Article
        fields ='__all__' 
        exclude=['user']
        widgets={
            "date_entree":DateInput()
        }
    def __init__(self,user, *args, **kwargs):
     
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['categorie'].queryset =Categorie.objects.filter(user=user)
        self.fields['categorie'].required=False 

class NewSortir(forms.ModelForm):
    class Meta:
        model = Sortir
        fields ='__all__'
        exclude = ['user', 'prix_sortie']
        widgets={
            'date_sortie':DateInput()
        }
    def clean(self):
        article = self.cleaned_data['article']
        qte = self.cleaned_data['qte']
        if (qte > article.quantity):
            raise forms.ValidationError("la quantité n'est pas disponible dans le stock")
        # ValueError("la quantité n'est pas disponible dans le stock")
    def __init__(self, *args, **kwargs):
        super(NewSortir, self).__init__(*args, **kwargs)
        self.fields['qte']=forms.IntegerField(min_value=1)

 

class NewFacture(forms.ModelForm):
    class Meta:
        model = Facture
        fields ='__all__'  
        exclude =['totalprix'] 
        widgets={
            'dateFacture': DateInput()
        } 

class NewBoutique(forms.ModelForm):
    class Meta:
        model = Boutique
        fields ='__all__' 

stock/templates/stock/cart_detail.html
{% load crispy_forms_tags %}
    <thead>
        <tr>
            <th>Article</th>
            <th>quantité</th>
            <th>prix de chat</th>
            <th>prix</th>
            <th>enlever</th>
        </tr>
    </thead>
    
        {%for item in cart %}
       
        <tr>
            <td>{{item.article.nom}}</td>
            <td>
                <form action="{% url 'stock:cart_add'%}" method="post">
                    <div class="row">
                        <div class="col-6">
                            {{item.update_quantity.quantity}}
                            {{item.update_quantity.override}}
                        </div>
                       
                    <div class="col-6"><button type="submit" class="btn-sm btn-primary"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bag-plus-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zM8.5 8a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V12a.5.5 0 0 0 1 0v-1.5H10a.5.5 0 0 0 0-1H8.5V8z"/>
                      </svg>
                    </button>
                    </div>
                    
                    </div>
                    
                   
                    {%csrf_token%}
                </form>
            </td>
            <td>
               {{ item.prix_achat}}
            </td>
            <td>{{item.total_prix}}</td>
            <td>
                <form action="{% url 'stock:cart_remove' item.article.numero%}" method="post">
                    {%csrf_token%}
                    <!-- <input type="hidden" name=""> -->
                    <button type="submit" class ='btn btn-danger'name="">evleve</button>
                </form>
            </td>
        </tr>
        
        {%endfor%}
        <tr>
            <td>Total:</td>
            <td colspan="3"></td>
            <td>{{cart.get_total_prix}}</td> 
        </tr>
    </tbody>

stock/templates/stock/sortirform.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-wrapper">

  <div class="container-fluid">
    
    <!-- Modal -->
  <!--  <div class="modal fade" id="myModal" role="dialog">-->
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" >Sortir Des Articles</h4>
  
                     <button type="button" class="close" data-dismiss="modal">
                         <a href=""  >&times;</a>
                     </button>
  
  
          </div>
          <div class="modal-body">
                 {% if messages %}
                   {% for message in messages %}
                       <div class="alert alert-{{message.tags}}">
                          {{message}}
                       </div>
                   {% endfor %}
                 {% endif %}
            <!--    form      -->
            
        <form method="POST" id="sortir_form" data-articles-url="{% url 'stock:load_articles_out'%}" data-stocks-url="{% url 'stock:load_stock_out' %}">
             {% csrf_token %}
             
             
             {{sortir_Form.categorie|as_crispy_field}}
             {{sortir_Form.stock|as_crispy_field}}
             {{sortir_Form.article|as_crispy_field}}
             <input type="text" class='form-control' value="la quantité dans le stock est " disabled="disabled">

             {{sortir_Form.qte|as_crispy_field}}
             {{sortir_Form.date_sortie|as_crispy_field}}






        
  
  
                    <div class="mt-6">
                         <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Add</button>
                      <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
                    </div>
  
        </form>

          </div>
          <div class="modal-footer">
                   <a href=""  >
                         <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
                            Close
                         </button>
                   </a>
          </div>
  
  
            <!--   endform         -->
        </div>
      </div>
  <!--  </div>-->
       
   </div>
   {% include 'stock/include_footer.html' %}
</div>

  
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $('#id_stock').change(function(){
      var url =$('#sortir_form').attr("data-articles-url");
      var stock=$(this).val();
      $.ajax({
        url : url,
        data:{
          'stock':stock
        },
        success: function(data){
          $("#id_article").html(data);
        }
      });
    });
    $('#id_categorie').change(function(){
      var url =$('#sortir_form').attr("data-stocks-url");
      var cat=$(this).val();
      $.ajax({
        url : url,
        data:{
          'categorie':cat
        },
        success: function(data){
          $("#id_stock").html(data);
        }
      });
    });
</script>
{% endblock content %}

stock/templates/stock/stockform.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-wrapper">

  <div class="container-fluid">
    
    <!-- Modal -->
  <!--  <div class="modal fade" id="myModal" role="dialog">-->
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" >Ajouter une nouvelle Stock</h4>
  
                     <button type="button" class="close" data-dismiss="modal">
                         <a href=""  >&times;</a>
                     </button>
  
  
                       </div>
                     <div class="modal-body">
                           {% if messages %}
                           {% for message in messages %}
                          <div class="alert alert-{{message.tags}}">
                          {{message}}
                          </div>
                             {% endfor %}
                              {% endif %}
                              <!--    form      -->
                               <form method="POST" name ="form" id= "stock_Form" data-articles-url="{% url 'stock:load_articles'%}">
                             {% csrf_token %}
                             {{stock_Form|crispy}}
                             
                            <div class="mt-6">
                                      <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Add</button>
                                     <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
                                     </div>

                                </form>

                                </div>
                               <div class="modal-footer">
                             <a href=""  >
                                 <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
                                    Close
                                   </button>
                                  </a>
                                  </div>


                                  <!--   endform         -->
                                 </div>
                              </div>
                                    <!--  </div>-->
                                  </div>
                                  {% include 'stock/include_footer.html' %}
                               </div>
                                    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                                    <script>
                                      $('#id_categorie').change(function(){
                                        var url =$('#stock_Form').attr("data-articles-url");
                                        var categorieId=$(this).val();
                                        $.ajax({
                                          url : url,
                                          data:{
                                            'categorie':categorieId
                                          },
                                          success: function(data){
                                            $("#id_article").html(data);
                                          }
                                        });
                                      });
                                    </script>
           {% endblock content %}
           

stock/templates/stock/table_user.html
{% extends 'base.html'%}
{% block content %}

{% load crispy_forms_tags %}

<div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">Table Utilisateur</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="{% url 'stock:home' %}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'accounts:signup' %}">Ajouter des utilisateur</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Table des utilisateur</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->
                   <div class="row">
                <div class="col-xl-12">
                      <div class="card card-shadow mb-4 ">
                            <div class="card-header border-0">
                                <div class="custom-title-wrap bar-warning">
                                    <div class="custom-title">Tables des utilisateur</div>
                                   
                                    <div class=" widget-action-link">
                                      {% if request.user.is_staff %}

                                        <div class="dropdown">
                                            <a href="#" class="btn btn-transparent text-secondary dropdown-hover p-0" data-toggle="dropdown">
                                                Action <i class="fa fa-caret-down pl-2"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right vl-dropdown">
                                                 <a class="dropdown-item" href="{% url 'accounts:signup'%}">Ajout de utilisateur</a>
                                                <a class="dropdown-item" id="action_move_auther_group" href="#"> Move to another group</a>
                                                <a class="dropdown-item" id="action_delete" href=""> Delete</a>
                                                <form method="" id='update_form' action="">
                                                    <input type="hidden" name="id_user" id='id_user' value="">
                                                    <button class="dropdown-item" type='submit' id="action_update">Modifier</button>
                                                </form>
                                                
                                                <a class="dropdown-item" id="action" href="#"> Send Message</a>
                                            </div>
                                        </div>
                                         {%endif%}

                                    </div>
                                </div>
                            </div>
                        <div class="card-body- pt-3 pb-4">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered table-striped" cellspacing="0">

                                    <thead>

                                    <tr>
                                       <th scope="col"></th>
                                            <th scope="col">Nom d’utilisateur</th>
                                            <th scope="col">Phone</th>
                                            <th scope="col">Adresse électronique</th>
                                            <th scope="col">Prénom</th>
                                            <th scope="col">Nom</th>
                                            <th scope="col">Status utilisateur</th>
                                    </tr>
                                    </thead>
                                    <tfoot>

                                    <tr>
                                         <th scope="col" clospan="7"></th>
                                            <th scope="col"></th>
                                            <th scope="col"></th>
                                            <th scope="col"> </th>
                                            <th scope="col"></th>
                                            <th scope="col"></th>
                                            <th scope="col"> </th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                     {% for p in user %}
                                        <tr>
                                            <td class="action-checkbox"> 

                                                   {% if request.user.is_superuser %}
                                                             <input type="checkbox" name="_selected_action"  value="{{p.id}}" class="action-select" >
                                                   {%endif%}



                                                <img class="rounded-circle mr-3 table-thumb" src="{{p.profile.image.url}}" width="30px"  alt=""/>

                                            </td>
                                            <td><a href="{% url 'stock:ajax_update' %}">{{p.username}}</a></td>
                                            <td>{{p.phone_number}}</td>
                                            <td>{{p.email}}</td>
                                            <td>{{p.first_name}}</td>
                                            <td>{{p.last_name}}</td>

                                            <td>
                                                {% if p.is_staff%}
                                                <center>Admin</center>
                                                {% else %}
                                                
                                                <center>Superviseur</center>
                                                   {% endif %}
                                            </td>


                                        </tr>

                                        {%endfor%}
                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
<!--    footer -->
     {% include 'stock/include_footer.html' %}



    </div>
<script>
function getCheckboxes() {
        return document.querySelectorAll('input[type=checkbox]');
    }

    function uncheckAllCheckboxes() {
        var checkboxes = getCheckboxes();

        for (var i = 0, length = checkboxes.length; i < length; i++) {
            checkboxes[i].checked = false;
            // return false;
        }
        // return true;
    }

    function manageClick() {
        uncheckAllCheckboxes();

        this.checked = true;
    return true;
    }

    function init() {
        var checkboxes = getCheckboxes();

        for (var i = 0, length = checkboxes.length; i < length; i++) {
            checkboxes[i].addEventListener('click', manageClick);
        }
    }

    init();

    //ajx 
    
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

$(document).ready(function() {
    $('#action_delete').click(function() {
        if (confirm('Vous etes sur? ')) {
            
       
            var id_user=[];
            $(':checkbox:checked').each(function(i){
              id_user[i]=$(this).val();
            });
            if (id_user.length===0) {
                alert('Please select a user to delete');
            }else{
                $.ajax({
                    url: '{% url "stock:ajax_delete" %}',
                    
                    data:{
                        id_user
                    }
                })
            }
        }
    })
});
$(document).ready(function() {
    $('#action_update').click(function() {
            var id_user=[];
            $(':checkbox:checked').each(function(i){
              id_user[i]=$(this).val();
            });
            if (id_user.length===0) {
                alert('Please select a user to delete');
            }
            else{
                $.ajax({
                    
                    
                    data:{
                        
                    }
                });
            }
       
    })
});
$(document).ready(function() {
    // var selected = []
$('input[type=checkbox]').change(function() {
    var id_user=[];
            $(':checkbox:checked').each(function(i){
              id_user[i]=$(this).val();
            });
            if (id_user.length===0) {
                

                alert('Please select a user to delete');
                
                            
            }
            else{
            $('#id_user').attr('value',id_user[0])}
            $('#update_form').attr('action', '{% url "stock:ajax_update"%}')
            $('#update_form').attr('method', 'GET')
})
})
</script>
{% endblock content %}