CSA/urls.py
from django.urls import include, path
from . import views

app_name = 'CSA'

urlpatterns = [
    path('', views.expediton, name='expedition')

]

Stocki/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('stock.urls', namespace='stock')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('client/', include('client.urls', namespace='client')),
    path('CSA/',include('CSA.urls', namespace='CSA')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name='chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('room/', views.room, name='room'),
    path('room_message/user_id=<int:pk>/send_message',views.room_message,name='room_message'),
    path('ajax/<int:pk>/loads',views.ajax_load_messages,name='ajax_load_messages'),
    
]

templates/base_form.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<!-- Mirrored from thevectorlab.net/dashlab-v1.3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Feb 2019 05:37:41 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">

    <!--favicon icon-->
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.html' %}">

    {% if title %}
    <title> {{title}}</title>
    {% else %}
    <title>title</title>
    {% endif %}
     <!--    icon-->
     <!--     <link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}">-->

    <!--web fonts-->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <!--bootstrap styles-->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--icon font-->
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/dashlab-icon/dashlab-icon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/themify-icons/css/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/weather-icons/css/weather-icons.min.css' %}" rel="stylesheet">

    <!--custom scrollbar-->
    <link href="{% static 'assets/vendor/m-custom-scrollbar/jquery.mCustomScrollbar.css' %}" rel="stylesheet">

    <!--jquery dropdown-->
    <link href="{% static 'assets/vendor/jquery-dropdown-master/jquery.dropdown.css' %}" rel="stylesheet">

    <!--jquery ui-->
    <link href="{% static 'assets/vendor/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">

    <!--iCheck-->
    <link href="{% static 'assets/vendor/icheck/skins/all.css' %}" rel="stylesheet">

    <!--vector maps -->
    <link href="{% static 'assets/vendor/vector-map/jquery-jvectormap-1.1.1.css' %}" rel="stylesheet" >

    <!--c3chart-->
    <link href="{% static 'assets/vendor/c3chart/c3.min.css' %}" rel="stylesheet">

        <!--data table-->
    <link href="{% static 'assets/vendor/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    <!--custom styles-->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'assets/vendor/html5shiv.js' %}"></script>
    <script src="{% static 'assets/vendor/respond.min.js' %}"></script>
    <![endif]-->
</head>
<body>








    <!--         strarblock       -->

     {% block content%}
     {% endblock content%}

    <!--          endblock  -->



<!--basic scripts-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'assets/vendor/jquery-dropdown-master/jquery.dropdown.js' %}"></script>


    <script src="{% static 'assets/vendor/m-custom-scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'assets/vendor/icheck/skins/icheck.min.js' %}"></script>

     <!--datatables-->
    <script src="{% static 'assets/vendor/data-tables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/vendor/data-tables/dataTables.bootstrap4.min.js' %}"></script>

    <!--sparkline-->
    <script src="{% static 'assets/vendor/sparkline/jquery.sparkline.js' %}"></script>
    <!--sparkline initialization-->
    <script src="{% static 'assets/vendor/js-init/sparkline/init-sparkline.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/init-datatable.js' %}"></script>


    <!--c3chart-->
    <script src="{% static 'assets/vendor/c3chart/d3.min.js' %}"></script>
    <script src="{% static 'assets/vendor/c3chart/c3.min.js' %}"></script>
    <!--c3chart initialization-->
    <script src="{% static 'assets/vendor/js-init/c3chart/init-c3chart.js' %}"></script>

    <!--chartjs-->
    <script src="{% static 'assets/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <!--chartjs initialization-->
    <script src="{% static 'assets/vendor/js-init/chartjs/init-creative-state-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-area-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-line-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-doughnut-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-doughnut-chart2.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-sales-report-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-bubble-chart.js' %}"></script>

    <!--flot chart-->
    <script src="{% static 'assets/vendor/flot/jquery.flot.min.js' %}"></script>
    <script src="{% static 'assets/vendor/flot/jquery.flot.pie.min.js' %}"></script>
    <script src="{% static 'assets/vendor/flot/jquery.flot.tooltip.min.js' %}"></script>
    <!--flot chart initialization-->
    <script src="{% static 'assets/vendor/js-init/flot/init-flot-widget.js' %}"></script>

      <!--init ajax datatable-->
    <script src="{% static 'assets/vendor/js-init/init-ajax-datatable.js' %}"></script>

    <!--vectormap-->
    <script src="{% static 'assets/vendor/vector-map/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'assets/vendor/vector-map/jquery-jvectormap-world-mill-en.js' %}"></script>
    <!--vectormap initialization-->
    <script src="{% static 'assets/vendor/js-init/vmap/init-vmap-world.js' %}"></script>

    <!--[if lt IE 9]>
    <script src="{% static 'assets/vendor/modernizr.js' %}"></script>
    <![endif]-->

    <!--basic scripts initialization-->
    <script src="{% static 'assets/js/scripts.js' %}"></script>
</body>

<!-- Mirrored from thevectorlab.net/dashlab-v1.3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Feb 2019 05:38:32 GMT -->
</html>

templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<!-- Mirrored from thevectorlab.net/dashlab-v1.3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Feb 2019 05:37:41 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">

    <!--favicon icon-->
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.html' %}">
    {% if title %}
    <title> {{title}}</title>
    {% else %}
    <title></title>
    {% endif %}





    <!--web fonts-->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <!--bootstrap styles-->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--icon font-->
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/dashlab-icon/dashlab-icon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/themify-icons/css/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/weather-icons/css/weather-icons.min.css' %}" rel="stylesheet">

    <!--custom scrollbar-->
    <link href="{% static 'assets/vendor/m-custom-scrollbar/jquery.mCustomScrollbar.css' %}" rel="stylesheet">

    <!--jquery dropdown-->
    <link href="{% static 'assets/vendor/jquery-dropdown-master/jquery.dropdown.css' %}" rel="stylesheet">

    <!--jquery ui-->
    <link href="{% static 'assets/vendor/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">

    <!--iCheck-->
    <link href="{% static 'assets/vendor/icheck/skins/all.css' %}" rel="stylesheet">

    <!--vector maps -->
    <link href="{% static 'assets/vendor/vector-map/jquery-jvectormap-1.1.1.css' %}" rel="stylesheet" >

    <!--c3chart-->
    <link href="{% static 'assets/vendor/c3chart/c3.min.css' %}" rel="stylesheet">

        <!--data table-->
    <link href="{% static 'assets/vendor/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    <!--custom styles-->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'assets/vendor/html5shiv.js' %}"></script>
    <script src="{% static 'assets/vendor/respond.min.js' %}"></script>
    <![endif]-->
</head>



   <!--         strarblock       -->

     {% block content%}
     {% endblock content%}

    <!--          endblock  -->












 <!--/right sidebar-->

    <!--basic scripts-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'assets/vendor/jquery-dropdown-master/jquery.dropdown.js' %}"></script>


    <script src="{% static 'assets/vendor/m-custom-scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'assets/vendor/icheck/skins/icheck.min.js' %}"></script>

     <!--datatables-->
    <script src="{% static 'assets/vendor/data-tables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/vendor/data-tables/dataTables.bootstrap4.min.js' %}"></script>

    <!--sparkline-->
    <script src="{% static 'assets/vendor/sparkline/jquery.sparkline.js' %}"></script>
    <!--sparkline initialization-->
    <script src="{% static 'assets/vendor/js-init/sparkline/init-sparkline.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/init-datatable.js' %}"></script>


    <!--c3chart-->
    <script src="{% static 'assets/vendor/c3chart/d3.min.js' %}"></script>
    <script src="{% static 'assets/vendor/c3chart/c3.min.js' %}"></script>
    <!--c3chart initialization-->
    <script src="{% static 'assets/vendor/js-init/c3chart/init-c3chart.js' %}"></script>

    <!--chartjs-->
    <script src="{% static 'assets/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <!--chartjs initialization-->
    <script src="{% static 'assets/vendor/js-init/chartjs/init-creative-state-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-area-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-line-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-doughnut-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-doughnut-chart2.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-sales-report-chart.js' %}"></script>
    <script src="{% static 'assets/vendor/js-init/chartjs/init-bubble-chart.js' %}"></script>

    <!--flot chart-->
    <script src="{% static 'assets/vendor/flot/jquery.flot.min.js' %}"></script>
    <script src="{% static 'assets/vendor/flot/jquery.flot.pie.min.js' %}"></script>
    <script src="{% static 'assets/vendor/flot/jquery.flot.tooltip.min.js' %}"></script>
    <!--flot chart initialization-->
    <script src="{% static 'assets/vendor/js-init/flot/init-flot-widget.js' %}"></script>

      <!--init ajax datatable-->
    <script src="{% static 'assets/vendor/js-init/init-ajax-datatable.js' %}"></script>

    <!--vectormap-->
    <script src="{% static 'assets/vendor/vector-map/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'assets/vendor/vector-map/jquery-jvectormap-world-mill-en.js' %}"></script>
    <!--vectormap initialization-->
    <script src="{% static 'assets/vendor/js-init/vmap/init-vmap-world.js' %}"></script>

    <!--[if lt IE 9]>
    <script src="{% static 'assets/vendor/modernizr.js' %}"></script>
    <![endif]-->

    <!--basic scripts initialization-->
    <script src="{% static 'assets/js/scripts.js' %}"></script>
</body>

<!-- Mirrored from thevectorlab.net/dashlab-v1.3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Feb 2019 05:38:32 GMT -->
</html>

templates/base_message.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="{% static 'base.css' %}"  rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        {% block app_css %}
        {% endblock app_css %}
    </head>
    <body>
        <div class="main-container">
          
            <div class="room-sidebar">
                <!-- room side bar header-->
                <div class="room-sidebar-header">
                    <div class="sb-avatar">
                        <img src="{{request.user.profile.image.url}}" alt="Default Profile">
                    </div>
                    <div class="sb-status">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path  d="M12 20.664a9.163 9.163 0 0 1-6.521-2.702.977.977 0 0 1 1.381-1.381 7.269 7.269 0 0 0 10.024.244.977.977 0 0 1 1.313 1.445A9.192 9.192 0 0 1 12 20.664zm7.965-6.112a.977.977 0 0 1-.944-1.229 7.26 7.26 0 0 0-4.8-8.804.977.977 0 0 1 .594-1.86 9.212 9.212 0 0 1 6.092 11.169.976.976 0 0 1-.942.724zm-16.025-.39a.977.977 0 0 1-.953-.769 9.21 9.21 0 0 1 6.626-10.86.975.975 0 1 1 .52 1.882l-.015.004a7.259 7.259 0 0 0-5.223 8.558.978.978 0 0 1-.955 1.185z"></path></svg>
                    </div>
                    <div class="sb-new-chat">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M19.005 3.175H4.674C3.642 3.175 3 3.789 3 4.821V21.02l3.544-3.514h12.461c1.033 0 2.064-1.06 2.064-2.093V4.821c-.001-1.032-1.032-1.646-2.064-1.646zm-4.989 9.869H7.041V11.1h6.975v1.944zm3-4H7.041V7.1h9.975v1.944z"></path></svg>
                    </div>
                    <div class="sb-menu">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M12 7a2 2 0 1 0-.001-4.001A2 2 0 0 0 12 7zm0 2a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 9zm0 6a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 15z"></path></svg>
                    </div>
                </div>
                <!-- room side bar header-->

                <!-- room side bar get notified -->
                <div class="room-sidebar-get-notified">
                    <div class="room-sidebar-get-notified-alert">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48"><path fill="white" d="M24.154 2C11.919 2 2 11.924 2 24.165S11.919 46.33 24.154 46.33s22.154-9.924 22.154-22.165S36.389 2 24.154 2zm-.744 15.428v-.618c0-.706.618-1.324 1.324-1.324s1.323.618 1.323 1.324v.618c2.559.618 4.412 2.823 4.412 5.559v3.176l-8.294-8.294a5.056 5.056 0 0 1 1.235-.441zm1.323 15.706a1.77 1.77 0 0 1-1.765-1.765h3.529a1.768 1.768 0 0 1-1.764 1.765zm7.236-.883l-1.765-1.765H17.233v-.882l1.765-1.765v-4.853a5.56 5.56 0 0 1 .794-2.912l-2.559-2.559 1.147-1.147 14.735 14.736-1.146 1.147z"></path></svg>
                    </div>
                    <div class="room-sidebar-get-notified-msg">
                        <span class="room-sidebar-get-notified-msg1">Get notified of  new messages</span>
                        <span class="room-sidebar-get-notified-msg2"><a href="javascript:void(0);alert('Coming Soon!')">Turn on desktop notifications</a>
                            <span class="room-sidebar-get-notified-arrow">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 12" width="8" height="12"><path fill="currentColor" d="M2.173 1l4.584 4.725-4.615 4.615-1.103-1.103 3.512-3.512L1 2.173 2.173 1z"></path></svg>
                            </span>
                        </span> 
                    </div>
                </div>
                <!-- room side bar get notified -->

                <!-- room side bar search or new chat -->
                <div class="room-sidebar-search-new-chat">
                    <div class="room-sidebar-search-new-chat2">
                        <div class="room-sidebar-search">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M15.009 13.805h-.636l-.22-.219a5.184 5.184 0 0 0 1.256-3.386 5.207 5.207 0 1 0-5.207 5.208 5.183 5.183 0 0 0 3.385-1.255l.221.22v.635l4.004 3.999 1.194-1.195-3.997-4.007zm-4.808 0a3.605 3.605 0 1 1 0-7.21 3.605 3.605 0 0 1 0 7.21z"></path></svg>
                        </div>
                        <div class="room-sidebar-new-chat">
                            <input type="text" placeholder="Search or start new chat"><br>
                        </div>
                    </div>
                </div>
                <!-- room side bar search or new chat -->

                <!-- room side bar groups -->
                {% if request.user.is_staff and request.user.is_superuser == False %}
                <a href="{% url 'chat:room_message' manangers.user.id %}"style='text-decoration:none'>

                    <div class="room-sidebar-groups" onclick="redirect('')">

                    <div class="room-sidebar-groups hover" onclick="redirect('')">

                    <div class="room-sidebar-groups hover-overlay" onclick="redirect('')">

                      
                                <div class="room-sidebar-groups-g-img">
                                    <img src="{{manangers.image.url}} " alt="Default Profile">
                                </div>
                                <div class="room-sidebar-groups-g-msg">
                                    <span class="room-sidebar-groups-g-msg1">{{manangers.user.username}}</span>
                                    {%for l in last %}
                                    {%if manangers.user == l.sender or manangers.user == l.receiver%}
                                    <span class="room-sidebar-groups-g-msg2 {% if l.seen %} text-muted{% else %}text-success{%endif%}" >{{l.message}}</span>
                                    {%endif%}
                                     {%endfor %}
                                </div>
                                <div class="flex-grow-1 text-right"  id='{{manangers.user.username}}'></div>
                                <!-- <div class="room-sidebar-groups-g-time" id="rsb-t{{grp.id}}"></div> -->
                               
                            
                            </div>
                        </a>
                {%else %}

                {% for manager in manangers%}
                <a href="{% url 'chat:room_message' manager.user.id %}"style='text-decoration:none'>
            <div class="room-sidebar-groups hover" onclick="redirect('')">
              
                        <div class="room-sidebar-groups-g-img">
                            <img src="{{manager.image.url}} " alt="Default Profile">
                        </div>
                        <div class="room-sidebar-groups-g-msg">
                            <span class="room-sidebar-groups-g-msg1">{{manager.user.username}}</span>
                            {%for l in last %}
                            {%if manager.user == l.sender or manager.user == l.receiver%}
                            <span class="room-sidebar-groups-g-msg2 {% if l.seen %} text-muted{% else %}text-success{%endif%}" >{{l.message}}</span>
                            {%endif%}
                             {%endfor %}
                        </div>
                       
                        <div class="flex-grow-1 text-right"  id='{{manager.user.username}}'>
                            
                            
                        </div>
                      
                 
                    </div>
                </a>
               {%endfor%}
               {%endif%}
                <!-- room side bar groups -->

            </div>
        {% block content %}
        {% endblock content %}
        {% block javascript %}
       
        {% endblock javascript %}
    </body> 
</html>